/*******************************************************************
* AUTHOR  : Abdelrahman Osam Khaled
* DATE	  : 1 May , 2023
* SWC 	  : RCC
* MC 	  : STM32F401X
* LAYER   : MCAL
* VERSION : V1.0
********************************************************************/

#include "STD_TYPES.h"
#include "BIT_MATH.h"

#include "RCC_interface.h"
#include "RCC_private.h"
#include "RCC_config.h"

void MRCC_voidInit(void)
{
	/* Select System clock */
	#if CPU_CLOCK_SELECTION == RCC_HSI
		/* Enable HSI clock source */
		SET_BIT(RCC_CR,RCC_CR_HSION);
		/* Select HSI as CPU clock source */
		CLEAR_BIT(RCC_CFGR,RCC_CFGR_SW0);
		CLEAR_BIT(RCC_CFGR,RCC_CFGR_SW1);
	#elif CPU_CLOCK_SELECTION == RCC_HSE
		/* Enable HSE clock source */
		SET_BIT(RCC_CR,RCC_CR_HSEON);
		/* Select HSE as CPU clock source */
		SET_BIT(RCC_CFGR,RCC_CFGR_SW0);
		CLEAR_BIT(RCC_CFGR,RCC_CFGR_SW1);
	#elif CPU_CLOCK_SELECTION == RCC_PLL
		#if PLL_CLOCK_SELECTION == RCC_HSI
			/* Enable HSI clock source */
			SET_BIT(RCC_CR,RCC_CR_HSION);
			/* Select HSI as PLL clock source */
			SET_BIT(RCC_PLLCFGR,RCC_PLLCFGR_PLLSRC);
			/* Enable PLL clock source */
			SET_BIT(RCC_CR,RCC_CR_PLLON);
			/* Select PLL as CPU clock source */
			CLEAR_BIT(RCC_CFGR,RCC_CFGR_SW0);
			SET_BIT(RCC_CFGR,RCC_CFGR_SW1);
		#elif PLL_CLOCK_SELECTION == RCC_HSE
			/* Enable HSE clock source */
			SET_BIT(RCC_CR,RCC_CR_HSEON);
			/* Select HSE as PLL clock source */
			CLEAR_BIT(RCC_PLLCFGR,RCC_PLLCFGR_PLLSRC);
			/* Enable PLL clock source */
			SET_BIT(RCC_CR,RCC_CR_PLLON);
			/* Select PLL as CPU clock source */
			CLEAR_BIT(RCC_CFGR,RCC_CFGR_SW0);
			SET_BIT(RCC_CFGR,RCC_CFGR_SW1);
		#else
			#error "Configuration Error : PLL clock selection error"
		#endif
	#else 
		#error "Configuration Error : CPU clock selection error"
	#endif
	
	#if AHB_PRESCALER_SELECTION == NO_PRESCALER
		CLEAR_BIT(RCC_CFGR,RCC_CFGR_HPRE3);
	#elif AHB_PRESCALER_SELECTION ==PRESCALER_DIVIDED_BY_2
		SET_BIT(RCC_CFGR,RCC_CFGR_HPRE3);
		CLEAR_BIT(RCC_CFGR,RCC_CFGR_HPRE2);
		CLEAR_BIT(RCC_CFGR,RCC_CFGR_HPRE1);
		CLEAR_BIT(RCC_CFGR,RCC_CFGR_HPRE0);
	#elif AHB_PRESCALER_SELECTION ==PRESCALER_DIVIDED_BY_4
		SET_BIT(RCC_CFGR,RCC_CFGR_HPRE3);
		CLEAR_BIT(RCC_CFGR,RCC_CFGR_HPRE2);
		CLEAR_BIT(RCC_CFGR,RCC_CFGR_HPRE1);
		SET_BIT(RCC_CFGR,RCC_CFGR_HPRE0);
	#elif AHB_PRESCALER_SELECTION ==PRESCALER_DIVIDED_BY_8
		SET_BIT(RCC_CFGR,RCC_CFGR_HPRE3);
		CLEAR_BIT(RCC_CFGR,RCC_CFGR_HPRE2);
		SET_BIT(RCC_CFGR,RCC_CFGR_HPRE1);
		CLEAR_BIT(RCC_CFGR,RCC_CFGR_HPRE0);
	#elif AHB_PRESCALER_SELECTION ==PRESCALER_DIVIDED_BY_16
		SET_BIT(RCC_CFGR,RCC_CFGR_HPRE3);
		CLEAR_BIT(RCC_CFGR,RCC_CFGR_HPRE2);
		SET_BIT(RCC_CFGR,RCC_CFGR_HPRE1);
		SET_BIT(RCC_CFGR,RCC_CFGR_HPRE0);
	#elif AHB_PRESCALER_SELECTION ==PRESCALER_DIVIDED_BY_64
		SET_BIT(RCC_CFGR,RCC_CFGR_HPRE3);
		SET_BIT(RCC_CFGR,RCC_CFGR_HPRE2);
		CLEAR_BIT(RCC_CFGR,RCC_CFGR_HPRE1);
		CLEAR_BIT(RCC_CFGR,RCC_CFGR_HPRE0);
	#elif AHB_PRESCALER_SELECTION ==PRESCALER_DIVIDED_BY_128
		SET_BIT(RCC_CFGR,RCC_CFGR_HPRE3);
		SET_BIT(RCC_CFGR,RCC_CFGR_HPRE2);
		CLEAR_BIT(RCC_CFGR,RCC_CFGR_HPRE1);
		SET_BIT(RCC_CFGR,RCC_CFGR_HPRE0);
	#elif AHB_PRESCALER_SELECTION ==PRESCALER_DIVIDED_BY_256
		SET_BIT(RCC_CFGR,RCC_CFGR_HPRE3);
		SET_BIT(RCC_CFGR,RCC_CFGR_HPRE2);
		SET_BIT(RCC_CFGR,RCC_CFGR_HPRE1);
		CLEAR_BIT(RCC_CFGR,RCC_CFGR_HPRE0);
	#elif AHB_PRESCALER_SELECTION ==PRESCALER_DIVIDED_BY_512
		SET_BIT(RCC_CFGR,RCC_CFGR_HPRE3);
		SET_BIT(RCC_CFGR,RCC_CFGR_HPRE2);
		SET_BIT(RCC_CFGR,RCC_CFGR_HPRE1);
		SET_BIT(RCC_CFGR,RCC_CFGR_HPRE0);
	#else
		#error "Configuration error : AHB prescaler selection error"
	#endif
	
	#if APB1_PRESCALER_SELECTION == NO_PRESCALER
		CLEAR_BIT(RCC_CFGR,RCC_CFGR_PPRE12);
	#elif APB1_PRESCALER_SELECTION == PRESCALER_DIVIDED_BY_2
		SET_BIT(RCC_CFGR,RCC_CFGR_PPRE12);
		CLEAR_BIT(RCC_CFGR,RCC_CFGR_PPRE11);
		CLEAR_BIT(RCC_CFGR,RCC_CFGR_PPRE10);
	#elif APB1_PRESCALER_SELECTION == PRESCALER_DIVIDED_BY_4
		SET_BIT(RCC_CFGR,RCC_CFGR_PPRE12);
		CLEAR_BIT(RCC_CFGR,RCC_CFGR_PPRE11);
		SET_BIT(RCC_CFGR,RCC_CFGR_PPRE10);
	#elif APB1_PRESCALER_SELECTION == PRESCALER_DIVIDED_BY_8
		SET_BIT(RCC_CFGR,RCC_CFGR_PPRE12);
		SET_BIT(RCC_CFGR,RCC_CFGR_PPRE11);
		CLEAR_BIT(RCC_CFGR,RCC_CFGR_PPRE10);
	#elif APB1_PRESCALER_SELECTION == PRESCALER_DIVIDED_BY_16
		SET_BIT(RCC_CFGR,RCC_CFGR_PPRE12);
		SET_BIT(RCC_CFGR,RCC_CFGR_PPRE11);
		SET_BIT(RCC_CFGR,RCC_CFGR_PPRE10);
	#else
		#error "Configuration error : APB1 prescaler selection error"
	#endif
	
	#if APB2_PRESCALER_SELECTION == NO_PRESCALER
		CLEAR_BIT(RCC_CFGR,RCC_CFGR_PPRE22);
	#elif APB2_PRESCALER_SELECTION == PRESCALER_DIVIDED_BY_2
		SET_BIT(RCC_CFGR,RCC_CFGR_PPRE22);
		CLEAR_BIT(RCC_CFGR,RCC_CFGR_PPRE21);
		CLEAR_BIT(RCC_CFGR,RCC_CFGR_PPRE20);
	#elif APB2_PRESCALER_SELECTION == PRESCALER_DIVIDED_BY_4
		SET_BIT(RCC_CFGR,RCC_CFGR_PPRE22);
		CLEAR_BIT(RCC_CFGR,RCC_CFGR_PPRE21);
		SET_BIT(RCC_CFGR,RCC_CFGR_PPRE20);
	#elif APB2_PRESCALER_SELECTION == PRESCALER_DIVIDED_BY_8
		SET_BIT(RCC_CFGR,RCC_CFGR_PPRE22);
		SET_BIT(RCC_CFGR,RCC_CFGR_PPRE21);
		CLEAR_BIT(RCC_CFGR,RCC_CFGR_PPRE20);
	#elif APB2_PRESCALER_SELECTION == PRESCALER_DIVIDED_BY_16
		SET_BIT(RCC_CFGR,RCC_CFGR_PPRE22);
		SET_BIT(RCC_CFGR,RCC_CFGR_PPRE21);
		SET_BIT(RCC_CFGR,RCC_CFGR_PPRE20);
	#else
		#error "Configuration error : APB2 prescaler selection error"
	#endif
	
	#if MCO1_PRESCALER_SELECTION == NO_PRESCALER
		CLEAR_BIT(RCC_CFGR,RCC_CFGR_MCO1PRE2);
	#elif MCO1_PRESCALER_SELECTION == PRESCALER_DIVIDED_BY_2
		SET_BIT(RCC_CFGR,RCC_CFGR_MCO1PRE2);
		CLEAR_BIT(RCC_CFGR,RCC_CFGR_MCO1PRE1);
		CLEAR_BIT(RCC_CFGR,RCC_CFGR_MCO1PRE0);
	#elif MCO1_PRESCALER_SELECTION == PRESCALER_DIVIDED_BY_3
		SET_BIT(RCC_CFGR,RCC_CFGR_MCO1PRE2);
		CLEAR_BIT(RCC_CFGR,RCC_CFGR_MCO1PRE1);
		SET_BIT(RCC_CFGR,RCC_CFGR_MCO1PRE0);
	#elif MCO1_PRESCALER_SELECTION == PRESCALER_DIVIDED_BY_4
		SET_BIT(RCC_CFGR,RCC_CFGR_MCO1PRE2);
		SET_BIT(RCC_CFGR,RCC_CFGR_MCO1PRE1);
		CLEAR_BIT(RCC_CFGR,RCC_CFGR_MCO1PRE0);
	#elif MCO1_PRESCALER_SELECTION == PRESCALER_DIVIDED_BY_5
		SET_BIT(RCC_CFGR,RCC_CFGR_MCO1PRE2);
		SET_BIT(RCC_CFGR,RCC_CFGR_MCO1PRE1);
		SET_BIT(RCC_CFGR,RCC_CFGR_MCO1PRE0);
	#else
		#error "Configuration error : MCO1 prescaler selection error"
	#endif
	
	#if MCO2_PRESCALER_SELECTION == NO_PRESCALER
		CLEAR_BIT(RCC_CFGR,RCC_CFGR_MCO2PRE2);
	#elif MCO2_PRESCALER_SELECTION == PRESCALER_DIVIDED_BY_2
		SET_BIT(RCC_CFGR,RCC_CFGR_MCO2PRE2);
		CLEAR_BIT(RCC_CFGR,RCC_CFGR_MCO2PRE1);
		CLEAR_BIT(RCC_CFGR,RCC_CFGR_MCO2PRE0);
	#elif MCO2_PRESCALER_SELECTION == PRESCALER_DIVIDED_BY_3
		SET_BIT(RCC_CFGR,RCC_CFGR_MCO2PRE2);
		CLEAR_BIT(RCC_CFGR,RCC_CFGR_MCO2PRE1);
		SET_BIT(RCC_CFGR,RCC_CFGR_MCO2PRE0);
	#elif MCO2_PRESCALER_SELECTION == PRESCALER_DIVIDED_BY_4
		SET_BIT(RCC_CFGR,RCC_CFGR_MCO2PRE2);
		SET_BIT(RCC_CFGR,RCC_CFGR_MCO2PRE1);
		CLEAR_BIT(RCC_CFGR,RCC_CFGR_MCO2PRE0);
	#elif MCO2_PRESCALER_SELECTION == PRESCALER_DIVIDED_BY_5
		SET_BIT(RCC_CFGR,RCC_CFGR_MCO2PRE2);
		SET_BIT(RCC_CFGR,RCC_CFGR_MCO2PRE1);
		SET_BIT(RCC_CFGR,RCC_CFGR_MCO2PRE0);
	#else
		#error "Configuration error : MCO2 prescaler selection error"
	#endif
}

void MRCC_voidEnablePeripheralClock(u8 Copy_u8PeripheralBus,u8 Copy_u8PeripheralID)
{
	switch(Copy_u8PeripheralBus)
	{
		case RCC_AHB1 :
			SET_BIT(RCC_AHB1ENR,Copy_u8PeripheralID);
		break;
		case RCC_AHB2 :
			SET_BIT(RCC_AHB2ENR,Copy_u8PeripheralID);
		break;
		case RCC_APB1 :
			SET_BIT(RCC_APB1ENR,Copy_u8PeripheralID);
		break;
		case RCC_APB2 :
			SET_BIT(RCC_APB2ENR,Copy_u8PeripheralID);
		break;
		default :	//error state
		break;
	}
}

void MRCC_voidDisablePeripheralClock(u8 Copy_u8PeripheralBus,u8 Copy_u8PeripheralID)
{
	switch(Copy_u8PeripheralBus)
	{
		case RCC_AHB1 :
			CLEAR_BIT(RCC_AHB1ENR,Copy_u8PeripheralID);
		break;
		case RCC_AHB2 :
			CLEAR_BIT(RCC_AHB2ENR,Copy_u8PeripheralID);
		break;
		case RCC_APB1 :
			CLEAR_BIT(RCC_APB1ENR,Copy_u8PeripheralID);
		break;
		case RCC_APB2 :
			CLEAR_BIT(RCC_APB2ENR,Copy_u8PeripheralID);
		break;
		default :	//error state
		break;
	}
}
