/*******************************************************************
* AUTHOR  : Abdelrahman Osam Khaled
* DATE	  : 1 May , 2023
* SWC 	  : RCC
* MC 	  : STM32F401X
* LAYER   : MCAL
* VERSION : V1.0
			->V2.0 (Add Prescaler buses)
********************************************************************/

#ifndef RCC_CONFIG_H
#define RCC_CONFIG_H

#define CPU_CLOCK_SELECTION		RCC_HSE
/* Options :
			RCC_HSI
			RCC_HSE
			RCC_PLL
	*/
	
#define PLL_CLOCK_SELECTION		RCC_HSE
/* Options :
			RCC_HSI
			RCC_HSE
	*/
	
#define AHB_PRESCALER_SELECTION	PRESCALER_DIVIDED_BY_4
/* Options :
			NO_PRESCALER
			PRESCALER_DIVIDED_BY_2
			PRESCALER_DIVIDED_BY_4
			PRESCALER_DIVIDED_BY_8
			PRESCALER_DIVIDED_BY_16
			PRESCALER_DIVIDED_BY_64
			PRESCALER_DIVIDED_BY_128
			PRESCALER_DIVIDED_BY_256
			PRESCALER_DIVIDED_BY_512
	*/
#define APB1_PRESCALER_SELECTION	PRESCALER_DIVIDED_BY_8
/* Options :
			NO_PRESCALER
			PRESCALER_DIVIDED_BY_2
			PRESCALER_DIVIDED_BY_4
			PRESCALER_DIVIDED_BY_8
			PRESCALER_DIVIDED_BY_16
	*/
#define APB2_PRESCALER_SELECTION	PRESCALER_DIVIDED_BY_8
/* Options :
			NO_PRESCALER
			PRESCALER_DIVIDED_BY_2
			PRESCALER_DIVIDED_BY_4
			PRESCALER_DIVIDED_BY_8
			PRESCALER_DIVIDED_BY_16
	*/
#define MCO1_PRESCALER_SELECTION	PRESCALER_DIVIDED_BY_2
/* Options :
			NO_PRESCALER
			PRESCALER_DIVIDED_BY_2
			PRESCALER_DIVIDED_BY_3
			PRESCALER_DIVIDED_BY_4
			PRESCALER_DIVIDED_BY_5
	*/
#define MCO2_PRESCALER_SELECTION	PRESCALER_DIVIDED_BY_2
/* Options :
			NO_PRESCALER
			PRESCALER_DIVIDED_BY_2
			PRESCALER_DIVIDED_BY_3
			PRESCALER_DIVIDED_BY_4
			PRESCALER_DIVIDED_BY_5
	*/
#endif
