/*******************************************************************
* AUTHOR  : Abdelrahman Osam Khaled
* DATE	  : 2 May , 2023
* SWC 	  : GPIO
* MC 	  : STM32F401X
* LAYER   : MCAL
* VERSION : V1.0
********************************************************************/

#ifndef GPIO_CONFIG_H
#define GPIO_CONFIG_H

#define GPIOA_OUTPUT_MODE_SELECTION		GPIO_OUTPUT_PUSH_PULL
#define GPIOB_OUTPUT_MODE_SELECTION		GPIO_OUTPUT_PUSH_PULL
#define GPIOC_OUTPUT_MODE_SELECTION		GPIO_OUTPUT_PUSH_PULL
/*  Options :-
			GPIO_OUTPUT_PUSH_PULL
			GPIO_OUTPUT_OPEN_DRAIN
	*/
#define GPIOA_OUTPUT_SPEED_SELECTION	GPIO_MEDIUM_SPEED
#define GPIOB_OUTPUT_SPEED_SELECTION	GPIO_MEDIUM_SPEED
#define GPIOC_OUTPUT_SPEED_SELECTION	GPIO_HIGH_SPEED
/*  Options :-
			GPIO_LOW_SPEED
			GPIO_MEDIUM_SPEED
			GPIO_HIGH_SPEED
			GPIO_VERY_HIGH_SPEED
	*/
#define GPIOA_PULL_MODE_SELECTION	GPIO_NO_PULL	
#define GPIOB_PULL_MODE_SELECTION	GPIO_PULL_UP
#define GPIOC_PULL_MODE_SELECTION	GPIO_PULL_DOWN
/*  Options :-
			GPIO_NO_PULL	
			GPIO_PULL_UP
			GPIO_PULL_DOWN
	*/
#endif
