# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'analoggaugewidget_demo.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1701, 761)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(9, 9, 651, 731))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.formLayout = QtWidgets.QFormLayout(self.frame_2)
        self.formLayout.setObjectName("formLayout")
        self.label_28 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.SpeedLCD = QtWidgets.QLCDNumber(self.frame_2)
        self.SpeedLCD.setObjectName("SpeedLCD")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.SpeedLCD)
        self.widget = AnalogGaugeWidget(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(300, 300))
        self.widget.setMaximumSize(QtCore.QSize(600, 600))
        self.widget.setBaseSize(QtCore.QSize(300, 300))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.widget)
        self.label_32 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.ButtonDistance50 = QtWidgets.QPushButton(self.frame)
        self.ButtonDistance50.setGeometry(QtCore.QRect(1480, 70, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonDistance50.setFont(font)
        self.ButtonDistance50.setObjectName("ButtonDistance50")
        self.ButtonDistance75 = QtWidgets.QPushButton(self.frame)
        self.ButtonDistance75.setGeometry(QtCore.QRect(1480, 140, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonDistance75.setFont(font)
        self.ButtonDistance75.setObjectName("ButtonDistance75")
        self.ButtonDistance100 = QtWidgets.QPushButton(self.frame)
        self.ButtonDistance100.setGeometry(QtCore.QRect(1480, 210, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonDistance100.setFont(font)
        self.ButtonDistance100.setObjectName("ButtonDistance100")
        self.ButtonACC_ON = QtWidgets.QPushButton(self.frame)
        self.ButtonACC_ON.setGeometry(QtCore.QRect(1480, 580, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonACC_ON.setFont(font)
        self.ButtonACC_ON.setObjectName("ButtonACC_ON")
        self.ButtonCC_OFF = QtWidgets.QPushButton(self.frame)
        self.ButtonCC_OFF.setGeometry(QtCore.QRect(1480, 650, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonCC_OFF.setFont(font)
        self.ButtonCC_OFF.setObjectName("ButtonCC_OFF")
        self.TextCC_O_Mode = QtWidgets.QTextBrowser(self.frame)
        self.TextCC_O_Mode.setGeometry(QtCore.QRect(1150, 610, 171, 61))
        self.TextCC_O_Mode.setObjectName("TextCC_O_Mode")
        self.TextODistanceMode = QtWidgets.QTextBrowser(self.frame)
        self.TextODistanceMode.setGeometry(QtCore.QRect(1160, 150, 171, 61))
        self.TextODistanceMode.setObjectName("TextODistanceMode")
        self.label_29 = QtWidgets.QLabel(self.frame)
        self.label_29.setGeometry(QtCore.QRect(680, 130, 461, 95))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.frame)
        self.label_30.setGeometry(QtCore.QRect(680, 600, 351, 95))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.label_33 = QtWidgets.QLabel(self.frame)
        self.label_33.setGeometry(QtCore.QRect(1460, 20, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.frame)
        self.label_34.setGeometry(QtCore.QRect(1500, 520, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.label_31 = QtWidgets.QLabel(self.frame)
        self.label_31.setGeometry(QtCore.QRect(680, 380, 431, 95))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.Textspeed_Mode = QtWidgets.QTextBrowser(self.frame)
        self.Textspeed_Mode.setGeometry(QtCore.QRect(1150, 400, 171, 61))
        self.Textspeed_Mode.setObjectName("Textspeed_Mode")
        self.ButtonSpeed1 = QtWidgets.QPushButton(self.frame)
        self.ButtonSpeed1.setGeometry(QtCore.QRect(1480, 370, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonSpeed1.setFont(font)
        self.ButtonSpeed1.setObjectName("ButtonSpeed1")
        self.ButtonSpeed2 = QtWidgets.QPushButton(self.frame)
        self.ButtonSpeed2.setGeometry(QtCore.QRect(1480, 440, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonSpeed2.setFont(font)
        self.ButtonSpeed2.setObjectName("ButtonSpeed2")
        self.label_35 = QtWidgets.QLabel(self.frame)
        self.label_35.setGeometry(QtCore.QRect(1460, 310, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_2.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AnalogGaugeWidget_Demo"))
        self.label_28.setText(_translate("MainWindow", "ITI:NC|G1"))
        self.label_32.setText(_translate("MainWindow", "SPEED :"))
        self.ButtonDistance50.setText(_translate("MainWindow", "NEAR"))
        self.ButtonDistance75.setText(_translate("MainWindow", "MEDIUM"))
        self.ButtonDistance100.setText(_translate("MainWindow", "FAR"))
        self.ButtonACC_ON.setText(_translate("MainWindow", "ACC ON"))
        self.ButtonCC_OFF.setText(_translate("MainWindow", "ACC OFF"))
        self.TextCC_O_Mode.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.TextODistanceMode.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_29.setText(_translate("MainWindow", "Current distance range : "))
        self.label_30.setText(_translate("MainWindow", "Current CC mode :"))
        self.label_33.setText(_translate("MainWindow", "Distance ranges"))
        self.label_34.setText(_translate("MainWindow", "ACC Modes"))
        self.label_31.setText(_translate("MainWindow", "Current speed mode :"))
        self.Textspeed_Mode.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.ButtonSpeed1.setText(_translate("MainWindow", "Speed : 20"))
        self.ButtonSpeed2.setText(_translate("MainWindow", "Speed : 45"))
        self.label_35.setText(_translate("MainWindow", "Speed modes"))
from analoggaugewidget import AnalogGaugeWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
