# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'analoggaugewidget_demo.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1460, 761)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(9, 9, 651, 731))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.formLayout = QtWidgets.QFormLayout(self.frame_2)
        self.formLayout.setObjectName("formLayout")
        self.label_28 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.SpeedLCD = QtWidgets.QLCDNumber(self.frame_2)
        self.SpeedLCD.setObjectName("SpeedLCD")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.SpeedLCD)
        self.widget = AnalogGaugeWidget(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(300, 300))
        self.widget.setMaximumSize(QtCore.QSize(600, 600))
        self.widget.setBaseSize(QtCore.QSize(300, 300))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.widget)
        self.label_32 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.ButtonDistance50 = QtWidgets.QPushButton(self.frame)
        self.ButtonDistance50.setGeometry(QtCore.QRect(1250, 80, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonDistance50.setFont(font)
        self.ButtonDistance50.setObjectName("ButtonDistance50")
        self.ButtonDistance75 = QtWidgets.QPushButton(self.frame)
        self.ButtonDistance75.setGeometry(QtCore.QRect(1250, 150, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonDistance75.setFont(font)
        self.ButtonDistance75.setObjectName("ButtonDistance75")
        self.ButtonDistance100 = QtWidgets.QPushButton(self.frame)
        self.ButtonDistance100.setGeometry(QtCore.QRect(1250, 220, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonDistance100.setFont(font)
        self.ButtonDistance100.setObjectName("ButtonDistance100")
        self.ButtonACC_ON = QtWidgets.QPushButton(self.frame)
        self.ButtonACC_ON.setGeometry(QtCore.QRect(1260, 400, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonACC_ON.setFont(font)
        self.ButtonACC_ON.setObjectName("ButtonACC_ON")
        self.ButtonCC_OFF = QtWidgets.QPushButton(self.frame)
        self.ButtonCC_OFF.setGeometry(QtCore.QRect(1260, 560, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonCC_OFF.setFont(font)
        self.ButtonCC_OFF.setObjectName("ButtonCC_OFF")
        self.ButtonNCC_ON = QtWidgets.QPushButton(self.frame)
        self.ButtonNCC_ON.setGeometry(QtCore.QRect(1260, 480, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.ButtonNCC_ON.setFont(font)
        self.ButtonNCC_ON.setObjectName("ButtonNCC_ON")
        self.TextCC_O_Mode = QtWidgets.QTextBrowser(self.frame)
        self.TextCC_O_Mode.setGeometry(QtCore.QRect(1060, 430, 171, 61))
        self.TextCC_O_Mode.setObjectName("TextCC_O_Mode")
        self.TextOCC_Statue = QtWidgets.QTextBrowser(self.frame)
        self.TextOCC_Statue.setGeometry(QtCore.QRect(1060, 510, 171, 61))
        self.TextOCC_Statue.setObjectName("TextOCC_Statue")
        self.TextODistanceMode = QtWidgets.QTextBrowser(self.frame)
        self.TextODistanceMode.setGeometry(QtCore.QRect(1000, 120, 171, 61))
        self.TextODistanceMode.setObjectName("TextODistanceMode")
        self.label_29 = QtWidgets.QLabel(self.frame)
        self.label_29.setGeometry(QtCore.QRect(680, 100, 321, 95))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.frame)
        self.label_30.setGeometry(QtCore.QRect(670, 410, 351, 95))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.frame)
        self.label_31.setGeometry(QtCore.QRect(670, 500, 361, 95))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.label_33 = QtWidgets.QLabel(self.frame)
        self.label_33.setGeometry(QtCore.QRect(1230, 30, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.frame)
        self.label_34.setGeometry(QtCore.QRect(1280, 340, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_2.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AnalogGaugeWidget_Demo"))
        self.label_28.setText(_translate("MainWindow", "ITI:NC|G1"))
        self.label_32.setText(_translate("MainWindow", "SPEED :"))
        self.ButtonDistance50.setText(_translate("MainWindow", "Distance:50CM"))
        self.ButtonDistance75.setText(_translate("MainWindow", "Distance:75CM"))
        self.ButtonDistance100.setText(_translate("MainWindow", "Distance:100CM"))
        self.ButtonACC_ON.setText(_translate("MainWindow", "ACC ON"))
        self.ButtonCC_OFF.setText(_translate("MainWindow", "CC OFF"))
        self.ButtonNCC_ON.setText(_translate("MainWindow", "NCC ON"))
        self.TextCC_O_Mode.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p></body></html>"))
        self.TextOCC_Statue.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p></body></html>"))
        self.TextODistanceMode.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p></body></html>"))
        self.label_29.setText(_translate("MainWindow", "Current mode : "))
        self.label_30.setText(_translate("MainWindow", "Current CC mode :"))
        self.label_31.setText(_translate("MainWindow", "Current CC statue : "))
        self.label_33.setText(_translate("MainWindow", "Distance Modes"))
        self.label_34.setText(_translate("MainWindow", "CC Modes"))
from analoggaugewidget import AnalogGaugeWidget
